# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_auto_20170618_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='body',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
